title = "TKDさんちのブログ"
baseURL = "https://www.high-novice.com"
languageCode = "ja"
theme = "ananke"

DefaultContentLanguage = "ja"
hasCJKLanguage = true
summaryLength = 200
SectionPagesMenu = "main"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-110394052-1"
disqusShortname = "high-novice"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/images/profile.png"
  site_logo = ""
  custom_css = ["styles/amazon.css", "styles/global.css"]
  description = "勉強したことなどをアウトプットしていきたいブログ"
  amazonJpAffiliate = "tkd2017-22"
  facebook = ""
  twitter = "https://twitter.com/2017takeda"
  instagram = ""
  youtube = ""
  github = "https://github.com/TAKEDA-Takashi"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  body_classes = "japanese bg-near-white"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/default-site-top-image.jpg"
  recent_posts_number = 3

[permalinks]
  post = "/entry/:year/:month/:day/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[menu]

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    pre = "<i class='fa fa-heart'></i>"
    url = "/tags/"
    weight = 0

[markup.goldmark.renderer]
  unsafe = true
